name: Greetings
on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Hi there! 👋 Thank you for opening an issue! 
          Please provide detailed information about the problem you're experiencing, including steps to reproduce if possible. 
          We'll get back to you as soon as we can. 
          Happy collaborating! 🚀
        pr-message: |
          Hello contributor! 🌟 Thank you for your pull request!
          
          To help us review your PR effectively, please ensure:
          - Your changes are clearly described.
          - You've added tests if applicable.
          - Your code follows our coding standards.
          
          We appreciate your contribution! 🎉
